# Generated by Django 5.0.2 on 2024-02-21 03:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombres')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='nombres')),
                ('num_documento', models.CharField(max_length=10, unique=True, verbose_name='numero_documento')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='fecha_registro')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='fecha_creacion')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('age', models.PositiveBigIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%y/%m/%d')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.type')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
